name: Leakage
main: io.github.otvmonteiro.leak.leakage
version: 0.0.3
description: Places a random mob spawner near the player
commands:
  leak:
    Description: Creates a "monster leak" near the player
    Usage: Type /leak or /le to use
    Aliases: [le] 
  upperbound:
    Description: changes the upperbound to place random "monster leak" near player, standard is 10
    Usage: Type /upperbound [number] , where [number] is the new value for maximum leakage distance (X and Y)