name: Leakage
main: io.github.otvmonteiro.leak.leakage
version: 0.0.4
description: Places a random mob spawner near the player
commands:
  leak:
    description: Creates a "monster leak" near the player
    usage: Type /leak or /le to use
    aliases: [le] 
  upperbound:
    description: changes the upperbound to place random "monster leak" near player, standard is 10
    usage: Type /upperbound [number] , where [number] is the new value for maximum leakage distance (X and Z)